[project]
name = "autodiff-proto"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["numpy>=2.2.6", "polars>=1.29.0", "sympy>=1.14.0"]

[dependency-groups]
dev = ["ruff>=0.11.10"]
